# Generated by Django 5.0.3 on 2024-05-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=20)),
                ('aemail', models.EmailField(max_length=40)),
                ('aphone', models.BigIntegerField()),
                ('aage', models.IntegerField()),
                ('agender', models.CharField(max_length=6)),
                ('astate', models.CharField(max_length=20)),
                ('acity', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'agents',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=20)),
                ('cemail', models.EmailField(max_length=40)),
                ('cphone', models.BigIntegerField()),
                ('cage', models.IntegerField()),
                ('cgender', models.CharField(max_length=6)),
                ('cstate', models.CharField(max_length=20)),
                ('ccity', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
