# Generated by Django 5.0.3 on 2024-05-15 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('policy_type', models.CharField(max_length=20)),
                ('policy_no', models.IntegerField()),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.agent')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
            ],
            options={
                'db_table': 'policy',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('claim_id', models.AutoField(primary_key=True, serialize=False)),
                ('claim_type', models.CharField(max_length=20)),
                ('amount', models.BigIntegerField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
                ('policy_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.policy')),
            ],
            options={
                'db_table': 'claims',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('transaction_date', models.DateField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
                ('policy_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.policy')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
