# Generated by Django 5.0.3 on 2024-05-20 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_policydetails_validity_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policydetails',
            name='amount_to_be_paid',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ClaimDetails',
            fields=[
                ('claim_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('end_of_policy_period_claim', models.BigIntegerField()),
                ('accident_claim_amount', models.BigIntegerField()),
                ('delayed_claim_amount', models.BigIntegerField()),
                ('time_to_claim_delayed_amount', models.IntegerField()),
                ('policy_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.policy')),
            ],
            options={
                'db_table': 'claim_details',
            },
        ),
    ]
