# Generated by Django 5.0.3 on 2024-05-20 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_policydetails_amount_to_be_paid_claimdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdetails',
            name='policy_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.policydetails'),
        ),
    ]
