# Generated by Django 5.0.3 on 2024-05-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_claimdetails_policy_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdetails',
            name='accident_claim_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claimdetails',
            name='delayed_claim_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claimdetails',
            name='end_of_policy_period_claim',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
