# Generated by Django 5.0.3 on 2024-05-21 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_claimdetails_accident_claim_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdetails',
            name='policy_no',
            field=models.ForeignKey(db_column='policy_no', on_delete=django.db.models.deletion.CASCADE, to='home.policydetails'),
        ),
    ]
