# Generated by Django 5.0.3 on 2024-05-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_claimdetails_policy_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='status',
            field=models.CharField(default='running', max_length=20),
        ),
    ]
